### ISSUE TITLE
Person in testament shows up dead while person is still alive

### ISSUE THREAD

**Issue by Brainscrewer** [OmertaBeyond/OBv2#114]
See http://prntscr.com/emspi4.
Version .nl

**Comment by Baelor** [comment]
This is due to the logger needing to be reset manually whenever a version ends.

If someone wants to start the work on migrating to the new logger, you can use the `users` endpoint for this (i.e. https://api.omertabeyond.net/domains/com/versions/latest/users/Grey). Alternatively, if someone's paying attention to the reset schedule of .nl, I can set you up with the reset script and db access. (I usually only pay attention to .com, unless someone nags me long enough about .nl.)
