### ISSUE TITLE
Prices in marquee wont show up

### ISSUE THREAD

**Issue by Ivdbroek85** [OmertaBeyond/OBv2#81]
as title says

**Comment by Baelor** [comment]
since we have less horizontal space on the top bar in newmerta, we'll probably have to split the marquee into multiple lines on smaller resolutions.
Example at width=1024:
![image](https://cloud.githubusercontent.com/assets/6425106/5772267/d93086ce-9d4f-11e4-80f4-ed52dba0230f.png)
width=1280:
![image](https://cloud.githubusercontent.com/assets/6425106/5772274/06e24ca6-9d50-11e4-8b75-cde32349abd0.png)

any other ideas?

**Comment by Ivdbroek85** [comment]
The idea behind the prices in marquee is to see at once what prices changed, instead of clicking to a new page. So the topbar is the only place for it. Guess we should split it in 2 lines then indeed. Or let people buy a bigger screen :P

**Comment by Baelor** [comment]
fixed in 7facb55
